export const ADVANCED = [
  {key:'IsCoChiBoDang', label: 'school.IsCoChiBoDang', value: '0'},
  {key:'IsTruongQuocTe', label: 'school.IsTruongQuocTe', value: '0'},
  {key:'IsVungDacBietKhoKhan', label: 'school.IsVungDacBietKhoKhan', value: '0'},
  {key:'IsHocSinhNoiTru', label: 'school.IsHocSinhNoiTru', value: '0'},
  {key:'IsSuDungMayTinhDayHoc', label: 'school.IsSuDungMayTinhDayHoc', value: '0'},
  {key:'IsCongTacTuVanHocDuong', label: 'school.IsCongTacTuVanHocDuong', value: '0'},
  {key:'IsKhaiThacInternetDayHoc', label: 'school.IsKhaiThacInternetDayHoc', value: '0'},
  {key:'IsDienLuoi', label: 'school.IsDienLuoi', value: '0'},
  {key:'IsKhiHauThienTai', label: 'school.IsKhiHauThienTai', value: '0'},
  {key:'IsNguonNuocSach', label: 'school.IsNguonNuocSach', value: '0'},
  {key:'IsCongTrinhVeSinh', label: 'school.IsCongTrinhVeSinh', value: '0'},
  {key:'IsHocSinhKhuyetTat', label: 'school.IsHocSinhKhuyetTat', value: '0'},
  {key:'IsCtGdvsDoiTay', label: 'school.IsCtGdvsDoiTay', value: '0'},
  {key:'IsChuongTrinhGiaoDucCoBan', label: 'school.IsChuongTrinhGiaoDucCoBan', value: '0'},
  {key:'IsHocSinhBanTru', label: 'school.IsHocSinhBanTru', value: '0'},
  {key:'IsCoHaTangTlhtPhuHopHskt', label: 'school.IsCoHaTangTlhtPhuHopHskt', value: '0'},
  {key:'IsDatChatLuongToiThieu', label: 'school.IsDatChatLuongToiThieu', value: '0'},
  {key:'IsKyNangSongGDXG', label: 'school.IsKyNangSongGDXG', value: '0'},
  {key:'IsChuyenBietKhuyetTat', label: 'school.IsChuyenBietKhuyetTat', value: '0'},
  {key:'IsHocChuongTrinhSongNgu', label: 'school.IsHocChuongTrinhSongNgu', value: '0'},
  {key:'IsTruongPtDtBanTru', label: 'school.IsTruongPtDtBanTru', value: '0'},
  {key:'IsActive', label: 'school.IsActive', value: '0'},
]

