export interface HomeroomClass {
  Avatar?: string,
  TenantId?: string,
  SchoolId?: string,
  SchoolYearId?: string,
  GradeId?: string,
  GradeName?: string,
  Code?: string,
  Name?: string,
  HomeroomTeacherId?: string,
  HomeroomTeacherName?: string,
  TeacherName?: string,
  ClassLeaderId?: string,
  ClassLeaderName?: string,
  ParentLeaderId?: string,
  ParentLeaderName?: string,
  IndexOrder?: number,
  ThuTu?: number,
  IsActive?: number | '0' | '1' | boolean,
  SignatureTeacher?: string,
  IsBilingual?: number | '0' | '1' | boolean,
  IsBanTru?: number | '0' | '1' | boolean,
  SoBuoiHocTrenTuan?: number | string,
  DiemTruong?: string,
  SoTietHocTrenTuan?: number | '',
  SachGiaoKhoa?: string,
  MaDanhMucNgoaiNgu1?: string,
  ChuongTrinhNN1?: string,
  SoTietNN1?: string,
  MaDanhMucNgoaiNgu2?: string,
  ChuongTrinhNN2?: string,
  SoTietNN2?: string,
  HocBanTru?: string,
  GhepVaoLop?: number | '',
  IsLopGhep?: number | '0' | '1' | boolean,
  IsBoTucTieuHoc?: number | '0' | '1' | boolean,
  IsXoaMuChu?: number | '0' | '1' | boolean,
  IsChuyenBiet?: number | '0' | '1' | boolean,
  IsVNEN?: number | '0' | '1' | boolean,
  IsTBDHTiengViet?: number | '0' | '1' | boolean,
  IsTBDHToan?: number | '0' | '1' | boolean,
  IsDaiDienChaMeLop?: number | '0' | '1' | boolean,
  IsDaiDienChaMeTruong?: number | '0' | '1' | boolean,
  IsGiaiThe?: number | '0' | '1' | boolean,
  IsCapNhatLopGhep?: number | '0' | '1' | boolean,
  Is2BuoiNgay?: number | '0' | '1' | boolean,
  IsHocNghe?: number | '0' | '1' | boolean,
  IsFreeDom?: number | '0' | '1' | boolean,
  IsDeleted?: number,
  CreatedBy?: string,
  UpdatedBy?: string,
  CreatedAt?: number,
  UpdatedAt?: number,
  NumberStudentTotal?: number,
  AttendancesStatus?: number,
  id?: string,
  TeacherAvatar?: string
}
